### ISSUE TITLE
Code Review 1 - Peter

### ISSUE THREAD

**Issue by pknibbe** [Iandris/myCine#2]
# Design/Code Review 1

#### Reviewer: Peter

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Problem Statement**|Yes|
| |Does the problem statement accurately describe project purpose?|Yes |
| |Is the problem statement professional? Think of prospective employers viewing this as part of the developer's portfolio.|Yes |
| |What is good?| Explanation of why and how it will work|
| |What could be improved?|Didn't see anything |
|**Design Documentation**|Does it exist?|yes |
| |Is the navigation/flow through the application logical and easy to use?| Yes |
| |Is the order in which the fields are displayed and form fields entered logical and easy to use?| Yes |
| |What data is missing?| Cost of rentals - money balance |
| |Is there data that is not used?| Not that I saw|
| |What is good?| lots of great ideas|
| |What could be improved?| better choices of which parts are core and which are stretch|
| **Data model**|Does it exist?| yes |
| |Is everything on the screens represented in the model?| I think so |
| |Does the model represent good database design? |yes |
| |What is good?| explicit join tables |
| |What could be better?|  don't know|
|**Additional design documents**| |no |
|**Application structure in IntelliJ**|Does it exist?| yes |
| |Is the structure correct for a Maven project?| yes |
| |Are packages and classs appropriately named?   | yes |
| |Other comments/notes?| classes don't exist yet|
|**JSPs**|Do they exist?| no |
| |Is templating used (for example, header.jsp, footer.jsp, etc.)?|N/A |
| |Is there business logic mixed in the JSPs?| N/A|
| |CSS?| N/A|
| |Other comments/notes?| Not yet. Mike will have to start coding soon|
|**Entities/DAOs/Controllers**|Do they exist?| Not yet|
|**Java code quality**|Are methods single-purpose?| Don't exist yet|
| |Are classes appropriately-sized classes (no monster classes)?| Don't exist yet|
| |Are the same lines of code repeated at all?| N/A| 
| |Do any classes perform very similar functions that could be candidates for super/subclass relationships?| N/A|
| |Are any values hard-coded that should be in a properties file?| N/A|
| |Are variable names descriptive?| N/A|
| |Are there many branches or loops that could be simplified or broken up into smaller methods?| N/A|
| |Do the DAOs use Hibernate? No hard-coded sql!| N/A|
| |Other comments/notes?|N/A |
|**Logging**|Has log4J been added?|N/A |
| |Are there logging statements in the code?| N/A|
| |Are appropriate logging levels used? Info, debug, error, for example.| N/A|
| |Are there any System.out.printlns in the code?| N/A|
| |Other comments/notes?|N/A |
|**Unit Tests**|Do they exist?| N/A|
| |Do the tests pass?| N/A|
| |What is the current code coverage?|N/A |
| |Is each test truly a unit test or are they functional tests?| N/A|
| |Other comments/notes?| N/A|
|**Web Service/API integration**|Has a web service/api been selected? | imdb |
| |What web services/apis might work well with this application?| imdb is a good choice|
|**Independent research topic**| Has a topic been selected?| Yes |
| |What topic/s might fit well in this application?| Security is a reasonable choice|

**Comment by pawaitemadisoncollege** [comment]
- [ ] Please update the formatting by adding a space between the left hand pipes. 
- [ ] indicate n/a if something is not applicable at this point.
